# Generated by Django 6.0.4 on 2026-04-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('bounty_for_information', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LostPetPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=200)),
                ('lost_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_my_lost_pet.lostpet')),
            ],
        ),
        migrations.AddField(
            model_name='lostpet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_my_lost_pet.user'),
        ),
    ]
