# Generated by Django 6.0.4 on 2026-04-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lost_pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
