# Generated by Django 6.0.4 on 2026-04-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lost_pet', '0002_rename_phonenumber_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
